{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "74e5eb9f-249e-437a-a568-3c300b96b90e",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Ans 1\n",
    "# The Exception class is the base class for all built-in, non-system-exiting exceptions in Python . When you create a custom exception class that inherits from the Exception class, you are essentially creating a new type of exception that behaves like any other built-in exception in Python."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "48253870-0bd4-43c7-a97d-301165a54558",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "ArithmeticError\n",
      "  > <class 'Exception'>\n",
      "  > Base class for arithmetic errors.\n",
      "\n",
      "AssertionError\n",
      "  > <class 'Exception'>\n",
      "  > Assertion failed.\n",
      "\n",
      "AttributeError\n",
      "  > <class 'Exception'>\n",
      "  > Attribute not found.\n",
      "\n",
      "BaseException\n",
      "  > <class 'object'>\n",
      "  > Common base class for all exceptions\n",
      "\n",
      "BlockingIOError\n",
      "  > <class 'OSError'>\n",
      "  > I/O operation would block.\n",
      "\n",
      "BrokenPipeError\n",
      "  > <class 'ConnectionError'>\n",
      "  > Broken pipe.\n",
      "\n",
      "BufferError\n",
      "  > <class 'Exception'>\n",
      "  > Buffer error.\n",
      "\n",
      "BytesWarning\n",
      "  > <class 'Warning'>\n",
      "  > Base class for warnings about bytes and buffer related problems, mostly\n",
      "related to conversion from str or comparing to str.\n",
      "\n",
      "ChildProcessError\n",
      "  > <class 'OSError'>\n",
      "  > Child process error.\n",
      "\n",
      "ConnectionAbortedError\n",
      "  > <class 'ConnectionError'>\n",
      "  > Connection aborted.\n",
      "\n",
      "ConnectionError\n",
      "  > <class 'OSError'>\n",
      "  > Connection error.\n",
      "\n",
      "ConnectionRefusedError\n",
      "  > <class 'ConnectionError'>\n",
      "  > Connection refused.\n",
      "\n",
      "ConnectionResetError\n",
      "  > <class 'ConnectionError'>\n",
      "  > Connection reset.\n",
      "\n",
      "DeprecationWarning\n",
      "  > <class 'Warning'>\n",
      "  > Base class for warnings about deprecated features.\n",
      "\n",
      "EOFError\n",
      "  > <class 'Exception'>\n",
      "  > Read beyond end of file.\n",
      "\n",
      "EncodingWarning\n",
      "  > <class 'Warning'>\n",
      "  > Base class for warnings about encodings.\n",
      "\n",
      "EnvironmentError\n",
      "  > <class 'Exception'>\n",
      "  > Base class for I/O related errors.\n",
      "\n",
      "Exception\n",
      "  > <class 'BaseException'>\n",
      "  > Common base class for all non-exit exceptions.\n",
      "\n",
      "FileExistsError\n",
      "  > <class 'OSError'>\n",
      "  > File already exists.\n",
      "\n",
      "FileNotFoundError\n",
      "  > <class 'OSError'>\n",
      "  > File not found.\n",
      "\n",
      "FloatingPointError\n",
      "  > <class 'ArithmeticError'>\n",
      "  > Floating point operation failed.\n",
      "\n",
      "FutureWarning\n",
      "  > <class 'Warning'>\n",
      "  > Base class for warnings about constructs that will change semantically\n",
      "in the future.\n",
      "\n",
      "GeneratorExit\n",
      "  > <class 'BaseException'>\n",
      "  > Request that a generator exit.\n",
      "\n",
      "IOError\n",
      "  > <class 'Exception'>\n",
      "  > Base class for I/O related errors.\n",
      "\n",
      "ImportError\n",
      "  > <class 'Exception'>\n",
      "  > Import can't find module, or can't find name in module.\n",
      "\n",
      "ImportWarning\n",
      "  > <class 'Warning'>\n",
      "  > Base class for warnings about probable mistakes in module imports\n",
      "\n",
      "IndentationError\n",
      "  > <class 'SyntaxError'>\n",
      "  > Improper indentation.\n",
      "\n",
      "IndexError\n",
      "  > <class 'LookupError'>\n",
      "  > Sequence index out of range.\n",
      "\n",
      "InterruptedError\n",
      "  > <class 'OSError'>\n",
      "  > Interrupted by signal.\n",
      "\n",
      "IsADirectoryError\n",
      "  > <class 'OSError'>\n",
      "  > Operation doesn't work on directories.\n",
      "\n",
      "KeyError\n",
      "  > <class 'LookupError'>\n",
      "  > Mapping key not found.\n",
      "\n",
      "KeyboardInterrupt\n",
      "  > <class 'BaseException'>\n",
      "  > Program interrupted by user.\n",
      "\n",
      "LookupError\n",
      "  > <class 'Exception'>\n",
      "  > Base class for lookup errors.\n",
      "\n",
      "MemoryError\n",
      "  > <class 'Exception'>\n",
      "  > Out of memory.\n",
      "\n",
      "ModuleNotFoundError\n",
      "  > <class 'ImportError'>\n",
      "  > Module not found.\n",
      "\n",
      "NameError\n",
      "  > <class 'Exception'>\n",
      "  > Name not found globally.\n",
      "\n",
      "NotADirectoryError\n",
      "  > <class 'OSError'>\n",
      "  > Operation only works on directories.\n",
      "\n",
      "NotImplementedError\n",
      "  > <class 'RuntimeError'>\n",
      "  > Method or function hasn't been implemented yet.\n",
      "\n",
      "OSError\n",
      "  > <class 'Exception'>\n",
      "  > Base class for I/O related errors.\n",
      "\n",
      "OverflowError\n",
      "  > <class 'ArithmeticError'>\n",
      "  > Result too large to be represented.\n",
      "\n",
      "PendingDeprecationWarning\n",
      "  > <class 'Warning'>\n",
      "  > Base class for warnings about features which will be deprecated\n",
      "in the future.\n",
      "\n",
      "PermissionError\n",
      "  > <class 'OSError'>\n",
      "  > Not enough permissions.\n",
      "\n",
      "ProcessLookupError\n",
      "  > <class 'OSError'>\n",
      "  > Process not found.\n",
      "\n",
      "RecursionError\n",
      "  > <class 'RuntimeError'>\n",
      "  > Recursion limit exceeded.\n",
      "\n",
      "ReferenceError\n",
      "  > <class 'Exception'>\n",
      "  > Weak ref proxy used after referent went away.\n",
      "\n",
      "ResourceWarning\n",
      "  > <class 'Warning'>\n",
      "  > Base class for warnings about resource usage.\n",
      "\n",
      "RuntimeError\n",
      "  > <class 'Exception'>\n",
      "  > Unspecified run-time error.\n",
      "\n",
      "RuntimeWarning\n",
      "  > <class 'Warning'>\n",
      "  > Base class for warnings about dubious runtime behavior.\n",
      "\n",
      "StopAsyncIteration\n",
      "  > <class 'Exception'>\n",
      "  > Signal the end from iterator.__anext__().\n",
      "\n",
      "StopIteration\n",
      "  > <class 'Exception'>\n",
      "  > Signal the end from iterator.__next__().\n",
      "\n",
      "SyntaxError\n",
      "  > <class 'Exception'>\n",
      "  > Invalid syntax.\n",
      "\n",
      "SyntaxWarning\n",
      "  > <class 'Warning'>\n",
      "  > Base class for warnings about dubious syntax.\n",
      "\n",
      "SystemError\n",
      "  > <class 'Exception'>\n",
      "  > Internal error in the Python interpreter.\n",
      "\n",
      "Please report this to the Python maintainer, along with the traceback,\n",
      "the Python version, and the hardware/OS platform and version.\n",
      "\n",
      "SystemExit\n",
      "  > <class 'BaseException'>\n",
      "  > Request to exit from the interpreter.\n",
      "\n",
      "TabError\n",
      "  > <class 'IndentationError'>\n",
      "  > Improper mixture of spaces and tabs.\n",
      "\n",
      "TimeoutError\n",
      "  > <class 'OSError'>\n",
      "  > Timeout expired.\n",
      "\n",
      "TypeError\n",
      "  > <class 'Exception'>\n",
      "  > Inappropriate argument type.\n",
      "\n",
      "UnboundLocalError\n",
      "  > <class 'NameError'>\n",
      "  > Local name referenced but not bound to a value.\n",
      "\n",
      "UnicodeDecodeError\n",
      "  > <class 'UnicodeError'>\n",
      "  > Unicode decoding error.\n",
      "\n",
      "UnicodeEncodeError\n",
      "  > <class 'UnicodeError'>\n",
      "  > Unicode encoding error.\n",
      "\n",
      "UnicodeError\n",
      "  > <class 'ValueError'>\n",
      "  > Unicode related error.\n",
      "\n",
      "UnicodeTranslateError\n",
      "  > <class 'UnicodeError'>\n",
      "  > Unicode translation error.\n",
      "\n",
      "UnicodeWarning\n",
      "  > <class 'Warning'>\n",
      "  > Base class for warnings about Unicode related problems, mostly\n",
      "related to conversion problems.\n",
      "\n",
      "UserWarning\n",
      "  > <class 'Warning'>\n",
      "  > Base class for warnings generated by user code.\n",
      "\n",
      "ValueError\n",
      "  > <class 'Exception'>\n",
      "  > Inappropriate argument value (of correct type).\n",
      "\n",
      "Warning\n",
      "  > <class 'Exception'>\n",
      "  > Base class for warning categories.\n",
      "\n",
      "ZeroDivisionError\n",
      "  > <class 'ArithmeticError'>\n",
      "  > Second argument to a division or modulo operation was zero.\n",
      "\n"
     ]
    }
   ],
   "source": [
    "# Ans 2\n",
    "import inspect\n",
    "\n",
    "def print_exception_hierarchy():\n",
    "    for name, obj in inspect.getmembers(__builtins__):\n",
    "        if inspect.isclass(obj) and issubclass(obj, BaseException):\n",
    "            print(name)\n",
    "            print(\"  >\", obj.__base__)\n",
    "            print(\"  >\", obj.__doc__)\n",
    "            print()\n",
    "\n",
    "print_exception_hierarchy()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "3507e7e9-99fd-49ec-8aa4-76814f2af257",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Dividing by zero :(    : division by zero\n",
      "Overflow error happened\n",
      " (34, 'Numerical result out of range'), <class 'OverflowError'>\n"
     ]
    }
   ],
   "source": [
    "# Ans 3\n",
    "# Errors defined in ArithmeticError class are:\n",
    "# ZeroDivision Error, OverfloError, FloatingPointerError, ValueError\n",
    "\n",
    "# ZeroDivision Error\n",
    "try:\n",
    "    7/0\n",
    "except ZeroDivisionError as r:\n",
    "    print(\"Dividing by zero :(    :\", r)\n",
    "\n",
    "# OverFlowError\n",
    "j = 5.0\n",
    "try:\n",
    "    for i in range (1, 1000):\n",
    "        j = j**i\n",
    "    print (j)\n",
    "except OverflowError as e:\n",
    "    print (\"Overflow error happened\")\n",
    "    print (f\" {e}, {e.__class__}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "39b4ad97-0495-4e9b-b189-77e9ede8e2e1",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Ans 4\n",
    "# The LookupError exception is the base class for errors raised when something can’t be found. It is used when a key or index used on a mapping or sequence is invalid 1.\n",
    "\n",
    "# KeyError and IndexError are two examples of exceptions that inherit from the LookupError class.\n",
    "\n",
    "# A KeyError is raised when you try to access a key that does not exist in a dictionary . For example, if you have a dictionary my_dict = {'a': 1, 'b': 2} and you try to access the value of the key ‘c’, you will get a KeyError because ‘c’ is not in the dictionary.\n",
    "\n",
    "# An IndexError is raised when you try to access an index that is out of range in a sequence like a list or tuple . For example, if you have a list my_list = [1, 2, 3] and you try to access the value at index 3 (which does not exist), you will get an IndexError."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "07ba959c-6518-434f-b1a9-d8c78aab2b0f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "The module could not be imported.\n",
      "The module could not be found.\n"
     ]
    }
   ],
   "source": [
    "# Ans 5\n",
    "\n",
    "# The ImportError exception is raised when a module or member of a module cannot be imported\n",
    "try:\n",
    "    import my_module\n",
    "except ImportError:\n",
    "    print(\"The module could not be imported.\")\n",
    "    \n",
    "    \n",
    "# The ModuleNotFoundError exception is raised when a module cannot be found.\n",
    "# This can happen if the module does not exist, is not installed, or is not in the correct location.\n",
    "try:\n",
    "    import my_module\n",
    "except ModuleNotFoundError:\n",
    "    print(\"The module could not be found.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4242c414-8c85-4c66-a8eb-547a401140f7",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Ans 6\n",
    "# Best practices are:\n",
    "\n",
    "# Always use specific exception\n",
    "# print always a proper message\n",
    "# always try to log your error\n",
    "# always avoid writing multiple exception handling\n",
    "# document alll errors with proper meaning\n",
    "# cleanup all resources"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
