{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "source": [
        "# In Python, all exceptions are instances of the built-in Exception class or one of its subclasses. When we create a custom exception, we are essentially creating a new subclass of the Exception class.\n",
        "\n",
        "# By inheriting from the Exception class, we can take advantage of the existing exception handling mechanisms in Python. This means that we can use the same try, except, and finally statements to handle our custom exception as we would for any built-in exception."
      ],
      "metadata": {
        "id": "d9gOHX-joFWP"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "def print_exception_hierarchy(exc_cls, indent=0):\n",
        "    print(' ' * indent + str(exc_cls))\n",
        "    for sub_cls in exc_cls.__subclasses__():\n",
        "        print_exception_hierarchy(sub_cls, indent + 4)\n",
        "\n",
        "print_exception_hierarchy(BaseException)\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "w7Sy5FHBoGy7",
        "outputId": "7bbac359-9b3e-4167-96f7-f66aa3727077"
      },
      "execution_count": 8,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "<class 'BaseException'>\n",
            "    <class 'Exception'>\n",
            "        <class 'TypeError'>\n",
            "            <class 'email.errors.MultipartConversionError'>\n",
            "            <class 'decimal.FloatOperation'>\n",
            "            <class 'numpy.core._exceptions.UFuncTypeError'>\n",
            "                <class 'numpy.core._exceptions._UFuncBinaryResolutionError'>\n",
            "                <class 'numpy.core._exceptions._UFuncNoLoopError'>\n",
            "                <class 'numpy.core._exceptions._UFuncCastingError'>\n",
            "                    <class 'numpy.core._exceptions._UFuncInputCastingError'>\n",
            "                    <class 'numpy.core._exceptions._UFuncOutputCastingError'>\n",
            "            <class 'matplotlib.units.ConversionError'>\n",
            "        <class 'StopAsyncIteration'>\n",
            "        <class 'StopIteration'>\n",
            "        <class 'ImportError'>\n",
            "            <class 'ModuleNotFoundError'>\n",
            "            <class 'zipimport.ZipImportError'>\n",
            "        <class 'OSError'>\n",
            "            <class 'ConnectionError'>\n",
            "                <class 'BrokenPipeError'>\n",
            "                <class 'ConnectionAbortedError'>\n",
            "                <class 'ConnectionRefusedError'>\n",
            "                <class 'ConnectionResetError'>\n",
            "                    <class 'http.client.RemoteDisconnected'>\n",
            "            <class 'BlockingIOError'>\n",
            "            <class 'ChildProcessError'>\n",
            "            <class 'FileExistsError'>\n",
            "            <class 'FileNotFoundError'>\n",
            "                <class 'matplotlib.ExecutableNotFoundError'>\n",
            "            <class 'IsADirectoryError'>\n",
            "            <class 'NotADirectoryError'>\n",
            "            <class 'InterruptedError'>\n",
            "                <class 'zmq.error.InterruptedSystemCall'>\n",
            "            <class 'PermissionError'>\n",
            "            <class 'ProcessLookupError'>\n",
            "            <class 'TimeoutError'>\n",
            "            <class 'io.UnsupportedOperation'>\n",
            "            <class 'signal.ItimerError'>\n",
            "            <class 'shutil.Error'>\n",
            "                <class 'shutil.SameFileError'>\n",
            "            <class 'shutil.SpecialFileError'>\n",
            "            <class 'shutil.ExecError'>\n",
            "            <class 'shutil.ReadError'>\n",
            "            <class 'socket.herror'>\n",
            "            <class 'socket.gaierror'>\n",
            "            <class 'socket.timeout'>\n",
            "            <class 'ssl.SSLError'>\n",
            "                <class 'ssl.SSLCertVerificationError'>\n",
            "                <class 'ssl.SSLZeroReturnError'>\n",
            "                <class 'ssl.SSLWantReadError'>\n",
            "                <class 'ssl.SSLWantWriteError'>\n",
            "                <class 'ssl.SSLSyscallError'>\n",
            "                <class 'ssl.SSLEOFError'>\n",
            "            <class 'urllib.error.URLError'>\n",
            "                <class 'urllib.error.HTTPError'>\n",
            "                <class 'urllib.error.ContentTooShortError'>\n",
            "            <class 'gzip.BadGzipFile'>\n",
            "            <class 'socks.ProxyError'>\n",
            "                <class 'socks.GeneralProxyError'>\n",
            "                <class 'socks.ProxyConnectionError'>\n",
            "                <class 'socks.SOCKS5AuthError'>\n",
            "                <class 'socks.SOCKS5Error'>\n",
            "                <class 'socks.SOCKS4Error'>\n",
            "                <class 'socks.HTTPError'>\n",
            "            <class 'PIL.UnidentifiedImageError'>\n",
            "        <class 'EOFError'>\n",
            "            <class 'asyncio.exceptions.IncompleteReadError'>\n",
            "        <class 'RuntimeError'>\n",
            "            <class 'RecursionError'>\n",
            "            <class 'NotImplementedError'>\n",
            "                <class 'IPython.core.error.StdinNotImplementedError'>\n",
            "                <class 'zmq.error.ZMQVersionError'>\n",
            "            <class '_frozen_importlib._DeadlockError'>\n",
            "            <class 'threading.BrokenBarrierError'>\n",
            "            <class 'concurrent.futures._base.BrokenExecutor'>\n",
            "                <class 'concurrent.futures.thread.BrokenThreadPool'>\n",
            "            <class 'asyncio.exceptions.SendfileNotAvailableError'>\n",
            "            <class 'numpy.TooHardError'>\n",
            "            <class 'pkg_resources.ExtractionError'>\n",
            "            <class '_pydevd_bundle.pydevd_vars.VariableError'>\n",
            "        <class 'NameError'>\n",
            "            <class 'UnboundLocalError'>\n",
            "        <class 'AttributeError'>\n",
            "            <class 'dataclasses.FrozenInstanceError'>\n",
            "        <class 'SyntaxError'>\n",
            "            <class 'IndentationError'>\n",
            "                <class 'TabError'>\n",
            "            <class 'xml.etree.ElementTree.ParseError'>\n",
            "        <class 'LookupError'>\n",
            "            <class 'IndexError'>\n",
            "                <class 'numpy.AxisError'>\n",
            "                <class 'matplotlib.streamplot.OutOfBounds'>\n",
            "            <class 'KeyError'>\n",
            "                <class 'IPython.terminal.pt_inputhooks.UnknownBackend'>\n",
            "                <class 'jupyter_client.kernelspec.NoSuchKernel'>\n",
            "            <class 'encodings.CodecRegistryError'>\n",
            "        <class 'ValueError'>\n",
            "            <class 'UnicodeError'>\n",
            "                <class 'UnicodeEncodeError'>\n",
            "                <class 'UnicodeDecodeError'>\n",
            "                <class 'UnicodeTranslateError'>\n",
            "            <class 'io.UnsupportedOperation'>\n",
            "            <class 'json.decoder.JSONDecodeError'>\n",
            "            <class 'binascii.Error'>\n",
            "            <class 'pygments.util.ClassNotFound'>\n",
            "            <class 'ssl.SSLCertVerificationError'>\n",
            "            <class 'IPython.lib.clipboard.ClipboardEmpty'>\n",
            "            <class 'email.errors.MessageDefect'>\n",
            "                <class 'email.errors.NoBoundaryInMultipartDefect'>\n",
            "                <class 'email.errors.StartBoundaryNotFoundDefect'>\n",
            "                <class 'email.errors.CloseBoundaryNotFoundDefect'>\n",
            "                <class 'email.errors.FirstHeaderLineIsContinuationDefect'>\n",
            "                <class 'email.errors.MisplacedEnvelopeHeaderDefect'>\n",
            "                <class 'email.errors.MissingHeaderBodySeparatorDefect'>\n",
            "                <class 'email.errors.MultipartInvariantViolationDefect'>\n",
            "                <class 'email.errors.InvalidMultipartContentTransferEncodingDefect'>\n",
            "                <class 'email.errors.UndecodableBytesDefect'>\n",
            "                <class 'email.errors.InvalidBase64PaddingDefect'>\n",
            "                <class 'email.errors.InvalidBase64CharactersDefect'>\n",
            "                <class 'email.errors.InvalidBase64LengthDefect'>\n",
            "                <class 'email.errors.HeaderDefect'>\n",
            "                    <class 'email.errors.InvalidHeaderDefect'>\n",
            "                    <class 'email.errors.HeaderMissingRequiredValue'>\n",
            "                    <class 'email.errors.NonPrintableDefect'>\n",
            "                    <class 'email.errors.ObsoleteHeaderDefect'>\n",
            "                    <class 'email.errors.NonASCIILocalPartDefect'>\n",
            "            <class 'calendar.IllegalMonthError'>\n",
            "            <class 'calendar.IllegalWeekdayError'>\n",
            "            <class 'IPython.core.magics.code.MacroToEdit'>\n",
            "            <class 'dateutil.parser._parser.ParserError'>\n",
            "            <class 'google.colab._import_hooks._cv2.DisabledFunctionError'>\n",
            "            <class 'numpy.AxisError'>\n",
            "            <class 'packaging.version.InvalidVersion'>\n",
            "            <class 'defusedxml.common.DefusedXmlException'>\n",
            "                <class 'defusedxml.common.DTDForbidden'>\n",
            "                <class 'defusedxml.common.EntitiesForbidden'>\n",
            "                <class 'defusedxml.common.ExternalReferenceForbidden'>\n",
            "                <class 'defusedxml.common.NotSupportedError'>\n",
            "            <class 'matplotlib.bezier.NonIntersectingPathException'>\n",
            "            <class 'plistlib.InvalidFileException'>\n",
            "            <class 'pkg_resources._vendor.more_itertools.recipes.UnequalIterablesError'>\n",
            "            <class 'pkg_resources.extern.packaging.version.InvalidVersion'>\n",
            "            <class 'pkg_resources._vendor.packaging._elffile.ELFInvalid'>\n",
            "            <class 'pkg_resources.extern.packaging.utils.InvalidWheelFilename'>\n",
            "            <class 'pkg_resources.extern.packaging.utils.InvalidSdistFilename'>\n",
            "            <class 'pkg_resources.extern.packaging.specifiers.InvalidSpecifier'>\n",
            "            <class 'pkg_resources.extern.packaging.markers.InvalidMarker'>\n",
            "            <class 'pkg_resources.extern.packaging.markers.UndefinedComparison'>\n",
            "            <class 'pkg_resources.extern.packaging.markers.UndefinedEnvironmentName'>\n",
            "            <class 'pkg_resources.extern.packaging.requirements.InvalidRequirement'>\n",
            "                <class 'pkg_resources.RequirementParseError'>\n",
            "        <class 'AssertionError'>\n",
            "        <class 'ArithmeticError'>\n",
            "            <class 'FloatingPointError'>\n",
            "            <class 'OverflowError'>\n",
            "            <class 'ZeroDivisionError'>\n",
            "                <class 'decimal.DivisionByZero'>\n",
            "                <class 'decimal.DivisionUndefined'>\n",
            "            <class 'decimal.DecimalException'>\n",
            "                <class 'decimal.Clamped'>\n",
            "                <class 'decimal.Rounded'>\n",
            "                    <class 'decimal.Underflow'>\n",
            "                    <class 'decimal.Overflow'>\n",
            "                <class 'decimal.Inexact'>\n",
            "                    <class 'decimal.Underflow'>\n",
            "                    <class 'decimal.Overflow'>\n",
            "                <class 'decimal.Subnormal'>\n",
            "                    <class 'decimal.Underflow'>\n",
            "                <class 'decimal.DivisionByZero'>\n",
            "                <class 'decimal.FloatOperation'>\n",
            "                <class 'decimal.InvalidOperation'>\n",
            "                    <class 'decimal.ConversionSyntax'>\n",
            "                    <class 'decimal.DivisionImpossible'>\n",
            "                    <class 'decimal.DivisionUndefined'>\n",
            "                    <class 'decimal.InvalidContext'>\n",
            "        <class 'SystemError'>\n",
            "            <class 'encodings.CodecRegistryError'>\n",
            "        <class 'ReferenceError'>\n",
            "        <class 'MemoryError'>\n",
            "            <class 'numpy.core._exceptions._ArrayMemoryError'>\n",
            "        <class 'BufferError'>\n",
            "        <class 'Warning'>\n",
            "            <class 'UserWarning'>\n",
            "                <class 'getpass.GetPassWarning'>\n",
            "                <class 'IPython.core.formatters.FormatterWarning'>\n",
            "                <class 'numpy.VisibleDeprecationWarning'>\n",
            "                <class 'numpy.RankWarning'>\n",
            "                <class 'numpy.lib._iotools.ConversionWarning'>\n",
            "                <class 'numpy.polynomial.polyutils.RankWarning'>\n",
            "            <class 'DeprecationWarning'>\n",
            "                <class 'IPython.core.interactiveshell.ProvisionalWarning'>\n",
            "                <class 'numpy.ModuleDeprecationWarning'>\n",
            "                <class 'matplotlib._api.deprecation.MatplotlibDeprecationWarning'>\n",
            "            <class 'PendingDeprecationWarning'>\n",
            "            <class 'SyntaxWarning'>\n",
            "            <class 'RuntimeWarning'>\n",
            "                <class 'zmq.asyncio.ProactorSelectorThreadWarning'>\n",
            "                <class 'dateutil.parser._parser.UnknownTimezoneWarning'>\n",
            "                <class 'numpy.ComplexWarning'>\n",
            "                <class 'PIL.Image.DecompressionBombWarning'>\n",
            "                <class 'pkg_resources.PEP440Warning'>\n",
            "            <class 'FutureWarning'>\n",
            "                <class 'IPython.core.completer.ProvisionalCompleterWarning'>\n",
            "                <class 'numpy.ma.core.MaskedArrayFutureWarning'>\n",
            "            <class 'ImportWarning'>\n",
            "            <class 'UnicodeWarning'>\n",
            "            <class 'BytesWarning'>\n",
            "            <class 'ResourceWarning'>\n",
            "            <class 'dateutil.tz.DeprecatedTzFormatWarning'>\n",
            "            <class 'matplotlib.mathtext.MathTextWarning'>\n",
            "            <class 'pkg_resources.PkgResourcesDeprecationWarning'>\n",
            "        <class 'warnings._OptionError'>\n",
            "        <class 're.error'>\n",
            "        <class 'sre_parse.Verbose'>\n",
            "        <class 'locale.Error'>\n",
            "        <class 'runpy._Error'>\n",
            "        <class 'subprocess.SubprocessError'>\n",
            "            <class 'subprocess.CalledProcessError'>\n",
            "            <class 'subprocess.TimeoutExpired'>\n",
            "        <class 'copy.Error'>\n",
            "        <class 'tokenize.TokenError'>\n",
            "        <class 'tokenize.StopTokenizing'>\n",
            "        <class 'zlib.error'>\n",
            "        <class '_lzma.LZMAError'>\n",
            "        <class 'shutil.RegistryError'>\n",
            "        <class 'shutil._GiveupOnFastCopy'>\n",
            "        <class 'inspect.ClassFoundException'>\n",
            "        <class 'inspect.EndOfBlock'>\n",
            "        <class 'traitlets.traitlets.TraitError'>\n",
            "        <class 'socket._GiveupOnSendfile'>\n",
            "        <class 'struct.error'>\n",
            "        <class '_pickle.PickleError'>\n",
            "            <class '_pickle.PicklingError'>\n",
            "            <class '_pickle.UnpicklingError'>\n",
            "        <class 'pickle._Stop'>\n",
            "        <class '_queue.Empty'>\n",
            "        <class 'queue.Full'>\n",
            "        <class 'argparse.ArgumentError'>\n",
            "        <class 'argparse.ArgumentTypeError'>\n",
            "        <class 'traitlets.config.loader.ConfigError'>\n",
            "            <class 'traitlets.config.loader.ConfigLoaderError'>\n",
            "                <class 'traitlets.config.loader.ArgumentError'>\n",
            "            <class 'traitlets.config.loader.ConfigFileNotFound'>\n",
            "        <class 'traitlets.config.configurable.ConfigurableError'>\n",
            "            <class 'traitlets.config.configurable.MultipleInstanceError'>\n",
            "        <class 'traitlets.config.application.ApplicationError'>\n",
            "        <class 'pydoc.ErrorDuringImport'>\n",
            "        <class 'bdb.BdbQuit'>\n",
            "        <class 'pdb.Restart'>\n",
            "        <class 'pexpect.exceptions.ExceptionPexpect'>\n",
            "            <class 'pexpect.exceptions.EOF'>\n",
            "            <class 'pexpect.exceptions.TIMEOUT'>\n",
            "        <class 'termios.error'>\n",
            "        <class 'ptyprocess.util.PtyProcessError'>\n",
            "        <class 'IPython.utils.process.FindCmdError'>\n",
            "        <class 'IPython.utils.path.HomeDirError'>\n",
            "        <class 'IPython.core.profiledir.ProfileDirError'>\n",
            "        <class 'IPython.core.error.IPythonCoreError'>\n",
            "            <class 'IPython.core.error.TryNext'>\n",
            "            <class 'IPython.core.error.UsageError'>\n",
            "            <class 'IPython.core.error.StdinNotImplementedError'>\n",
            "        <class 'IPython.core.error.InputRejected'>\n",
            "        <class 'getopt.GetoptError'>\n",
            "        <class 'binascii.Incomplete'>\n",
            "        <class 'pygments.util.OptionError'>\n",
            "        <class 'pygments.filters.ErrorToken'>\n",
            "        <class 'IPython.core.prefilter.PrefilterError'>\n",
            "        <class 'IPython.core.alias.AliasError'>\n",
            "            <class 'IPython.core.alias.InvalidAliasError'>\n",
            "        <class 'sqlite3.Error'>\n",
            "            <class 'sqlite3.InterfaceError'>\n",
            "            <class 'sqlite3.DatabaseError'>\n",
            "                <class 'sqlite3.InternalError'>\n",
            "                <class 'sqlite3.OperationalError'>\n",
            "                <class 'sqlite3.ProgrammingError'>\n",
            "                <class 'sqlite3.IntegrityError'>\n",
            "                <class 'sqlite3.DataError'>\n",
            "                <class 'sqlite3.NotSupportedError'>\n",
            "        <class 'sqlite3.Warning'>\n",
            "        <class 'concurrent.futures._base.Error'>\n",
            "            <class 'concurrent.futures._base.CancelledError'>\n",
            "            <class 'concurrent.futures._base.TimeoutError'>\n",
            "            <class 'concurrent.futures._base.InvalidStateError'>\n",
            "        <class 'asyncio.exceptions.TimeoutError'>\n",
            "        <class 'asyncio.exceptions.InvalidStateError'>\n",
            "        <class 'asyncio.exceptions.LimitOverrunError'>\n",
            "        <class 'asyncio.queues.QueueEmpty'>\n",
            "        <class 'asyncio.queues.QueueFull'>\n",
            "        <class 'IPython.core.interactiveshell.SpaceInInput'>\n",
            "        <class 'xml.dom.DOMException'>\n",
            "            <class 'xml.dom.IndexSizeErr'>\n",
            "            <class 'xml.dom.DomstringSizeErr'>\n",
            "            <class 'xml.dom.HierarchyRequestErr'>\n",
            "            <class 'xml.dom.WrongDocumentErr'>\n",
            "            <class 'xml.dom.InvalidCharacterErr'>\n",
            "            <class 'xml.dom.NoDataAllowedErr'>\n",
            "            <class 'xml.dom.NoModificationAllowedErr'>\n",
            "            <class 'xml.dom.NotFoundErr'>\n",
            "            <class 'xml.dom.NotSupportedErr'>\n",
            "            <class 'xml.dom.InuseAttributeErr'>\n",
            "            <class 'xml.dom.InvalidStateErr'>\n",
            "            <class 'xml.dom.SyntaxErr'>\n",
            "            <class 'xml.dom.InvalidModificationErr'>\n",
            "            <class 'xml.dom.NamespaceErr'>\n",
            "            <class 'xml.dom.InvalidAccessErr'>\n",
            "            <class 'xml.dom.ValidationErr'>\n",
            "        <class 'prompt_toolkit.validation.ValidationError'>\n",
            "        <class 'prompt_toolkit.buffer.EditReadOnlyBuffer'>\n",
            "        <class 'prompt_toolkit.buffer._Retry'>\n",
            "        <class 'prompt_toolkit.layout.layout.InvalidLayoutError'>\n",
            "        <class 'prompt_toolkit.renderer.HeightIsUnknownError'>\n",
            "        <class 'email.errors.MessageError'>\n",
            "            <class 'email.errors.MessageParseError'>\n",
            "                <class 'email.errors.HeaderParseError'>\n",
            "                <class 'email.errors.BoundaryError'>\n",
            "            <class 'email.errors.MultipartConversionError'>\n",
            "            <class 'email.errors.CharsetError'>\n",
            "        <class 'uu.Error'>\n",
            "        <class 'http.client.HTTPException'>\n",
            "            <class 'http.client.NotConnected'>\n",
            "            <class 'http.client.InvalidURL'>\n",
            "            <class 'http.client.UnknownProtocol'>\n",
            "            <class 'http.client.UnknownTransferEncoding'>\n",
            "            <class 'http.client.UnimplementedFileMode'>\n",
            "            <class 'http.client.IncompleteRead'>\n",
            "            <class 'http.client.ImproperConnectionState'>\n",
            "                <class 'http.client.CannotSendRequest'>\n",
            "                <class 'http.client.CannotSendHeader'>\n",
            "                <class 'http.client.ResponseNotReady'>\n",
            "            <class 'http.client.BadStatusLine'>\n",
            "                <class 'http.client.RemoteDisconnected'>\n",
            "            <class 'http.client.LineTooLong'>\n",
            "        <class 'IPython.core.magics.code.InteractivelyDefined'>\n",
            "        <class 'IPython.terminal.embed.KillEmbedded'>\n",
            "        <class 'ctypes.ArgumentError'>\n",
            "        <class 'zmq.error.ZMQBaseError'>\n",
            "            <class 'zmq.error.ZMQError'>\n",
            "                <class 'zmq.error.ContextTerminated'>\n",
            "                <class 'zmq.error.Again'>\n",
            "                <class 'zmq.error.InterruptedSystemCall'>\n",
            "            <class 'zmq.error.ZMQBindError'>\n",
            "            <class 'zmq.error.NotDone'>\n",
            "        <class 'jupyter_client.localinterfaces.NoIPAddresses'>\n",
            "        <class 'configparser.Error'>\n",
            "            <class 'configparser.NoSectionError'>\n",
            "            <class 'configparser.DuplicateSectionError'>\n",
            "            <class 'configparser.DuplicateOptionError'>\n",
            "            <class 'configparser.NoOptionError'>\n",
            "            <class 'configparser.InterpolationError'>\n",
            "                <class 'configparser.InterpolationMissingOptionError'>\n",
            "                <class 'configparser.InterpolationSyntaxError'>\n",
            "                <class 'configparser.InterpolationDepthError'>\n",
            "            <class 'configparser.ParsingError'>\n",
            "                <class 'configparser.MissingSectionHeaderError'>\n",
            "        <class 'jupyter_client.channels.InvalidPortNumber'>\n",
            "        <class 'jupyter_client.multikernelmanager.DuplicateKernelError'>\n",
            "        <class '_curses.error'>\n",
            "        <class 'tornado.concurrent.ReturnValueIgnoredError'>\n",
            "        <class 'tornado.gen.KeyReuseError'>\n",
            "        <class 'tornado.gen.UnknownKeyError'>\n",
            "        <class 'tornado.gen.LeakedCallbackError'>\n",
            "        <class 'tornado.gen.BadYieldError'>\n",
            "        <class 'tornado.gen.ReturnValueIgnoredError'>\n",
            "        <class 'tornado.gen.Return'>\n",
            "        <class 'tornado.queues.QueueEmpty'>\n",
            "        <class 'tornado.queues.QueueFull'>\n",
            "        <class 'google.colab.errors.Error'>\n",
            "            <class 'google.colab.errors.AuthorizationError'>\n",
            "            <class 'google.colab.errors.RuntimeManagementError'>\n",
            "            <class 'google.colab._message.MessageError'>\n",
            "        <class 'google.colab.errors.WidgetException'>\n",
            "        <class 'google.colab.output._js_builder.JsException'>\n",
            "        <class 'google.colab._shell_customizations.FormattedTracebackError'>\n",
            "        <class 'psutil.Error'>\n",
            "            <class 'psutil.NoSuchProcess'>\n",
            "                <class 'psutil.ZombieProcess'>\n",
            "            <class 'psutil.AccessDenied'>\n",
            "            <class 'psutil.TimeoutExpired'>\n",
            "        <class 'psutil._pslinux._Ipv6UnsupportedError'>\n",
            "        <class 'pyparsing.exceptions.ParseBaseException'>\n",
            "            <class 'pyparsing.exceptions.ParseException'>\n",
            "            <class 'pyparsing.exceptions.ParseFatalException'>\n",
            "                <class 'pyparsing.exceptions.ParseSyntaxException'>\n",
            "        <class 'pyparsing.exceptions.RecursiveGrammarException'>\n",
            "        <class 'httplib2.error.HttpLib2Error'>\n",
            "            <class 'httplib2.error.HttpLib2ErrorWithResponse'>\n",
            "                <class 'httplib2.error.RedirectMissingLocation'>\n",
            "                <class 'httplib2.error.RedirectLimit'>\n",
            "                <class 'httplib2.error.FailedToDecompressContent'>\n",
            "                <class 'httplib2.error.UnimplementedDigestAuthOptionError'>\n",
            "                <class 'httplib2.error.UnimplementedHmacDigestAuthOptionError'>\n",
            "            <class 'httplib2.error.MalformedHeader'>\n",
            "            <class 'httplib2.error.RelativeURIError'>\n",
            "            <class 'httplib2.error.ServerNotFoundError'>\n",
            "            <class 'httplib2.error.ProxiesUnavailableError'>\n",
            "        <class 'zipfile.BadZipFile'>\n",
            "        <class 'zipfile.LargeZipFile'>\n",
            "        <class 'numpy.linalg.LinAlgError'>\n",
            "        <class 'numpy.lib._iotools.ConverterError'>\n",
            "            <class 'numpy.lib._iotools.ConverterLockError'>\n",
            "        <class 'numpy.ma.core.MAError'>\n",
            "            <class 'numpy.ma.core.MaskError'>\n",
            "        <class 'xml.parsers.expat.ExpatError'>\n",
            "        <class 'PIL.Image.DecompressionBombError'>\n",
            "        <class 'cffi.FFIError'>\n",
            "        <class 'cffi.CDefError'>\n",
            "        <class 'cffi.VerificationError'>\n",
            "        <class 'cffi.VerificationMissing'>\n",
            "        <class 'cffi.PkgConfigError'>\n",
            "        <class 'kiwisolver.DuplicateConstraint'>\n",
            "        <class 'kiwisolver.UnsatisfiableConstraint'>\n",
            "        <class 'kiwisolver.UnknownConstraint'>\n",
            "        <class 'kiwisolver.DuplicateEditVariable'>\n",
            "        <class 'kiwisolver.UnknownEditVariable'>\n",
            "        <class 'kiwisolver.BadRequiredStrength'>\n",
            "        <class 'matplotlib.backend_bases.NonGuiException'>\n",
            "        <class 'matplotlib.streamplot.InvalidIndexError'>\n",
            "        <class 'matplotlib.streamplot.TerminateTrajectory'>\n",
            "        <class 'importlib_resources.abc.TraversalError'>\n",
            "        <class 'portpicker.NoFreePortFoundError'>\n",
            "        <class '_pydev_bundle._pydev_saved_modules.DebuggerInitializationError'>\n",
            "        <class 'xmlrpc.client.Error'>\n",
            "            <class 'xmlrpc.client.ProtocolError'>\n",
            "            <class 'xmlrpc.client.ResponseError'>\n",
            "            <class 'xmlrpc.client.Fault'>\n",
            "        <class 'pkg_resources.extern.packaging._tokenizer.ParserSyntaxError'>\n",
            "        <class 'pkg_resources.ResolutionError'>\n",
            "            <class 'pkg_resources.VersionConflict'>\n",
            "                <class 'pkg_resources.ContextualVersionConflict'>\n",
            "            <class 'pkg_resources.DistributionNotFound'>\n",
            "            <class 'pkg_resources.UnknownExtra'>\n",
            "        <class '_pydevd_bundle.pydevd_runpy._Error'>\n",
            "        <class '_pydevd_bundle.pydevd_resolver.UnableToResolveVariableException'>\n",
            "        <class '_pydev_bundle.pydev_monkey.InvalidTypeInArgsException'>\n",
            "        <class '__main__.NegativeNumberError'>\n",
            "    <class 'GeneratorExit'>\n",
            "    <class 'SystemExit'>\n",
            "    <class 'KeyboardInterrupt'>\n",
            "    <class 'asyncio.exceptions.CancelledError'>\n",
            "    <class 'pkg_resources._vendor.more_itertools.more.AbortThread'>\n"
          ]
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "# The ArithmeticError class is a built-in exception class in Python that is raised when there is an error during arithmetic operations. It is a subclass of the Exception class and a superclass of several other specific arithmetic exception classes."
      ],
      "metadata": {
        "id": "utP831dLoxJU"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "# ZeroDivisionError: This exception is raised when attempting to divide a number by zero.\n",
        "a = 5\n",
        "b = 0\n",
        "\n",
        "try:\n",
        "    c = a / b\n",
        "except ZeroDivisionError:\n",
        "    print(\"Error: division by zero\")\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "Y0WBGN5DoQrF",
        "outputId": "4b813e89-2f75-44ec-c8fe-7e4a0cbd75df"
      },
      "execution_count": 10,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Error: division by zero\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# OverflowError: This exception is raised when a calculation exceeds the maximum value that can be represented by a numeric type.\n",
        "import math\n",
        "\n",
        "try:\n",
        "    x = math.exp(1000)\n",
        "except OverflowError:\n",
        "    print(\"Error: calculation overflow\")\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "Ao_GfoM4o0X4",
        "outputId": "728c0c78-afc6-4008-9770-8e7e3b926a55"
      },
      "execution_count": 11,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Error: calculation overflow\n"
          ]
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "# The LookupError class is a built-in exception class in Python that is raised when an index or key lookup operation fails on a sequence or mapping object."
      ],
      "metadata": {
        "id": "pKdrJkvupL49"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "# KeyError: This exception is raised when a dictionary key is not found.\n",
        "d = {'a': 1, 'b': 2, 'c': 3}\n",
        "\n",
        "try:\n",
        "    value = d['d']\n",
        "except KeyError:\n",
        "    print(\"Error: key not found\")\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "hPisuMjwo-8T",
        "outputId": "ef2bcf01-aea2-4c8c-d993-0bba3a72723b"
      },
      "execution_count": 13,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Error: key not found\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# IndexError: This exception is raised when an index is out of range for a sequence.\n",
        "lst = [1, 2, 3]\n",
        "\n",
        "try:\n",
        "    value = lst[3]\n",
        "except IndexError:\n",
        "    print(\"Error: index out of range\")\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "ivV7I7HCpODl",
        "outputId": "98950443-3e18-4ca5-dee0-55beddd9d9ac"
      },
      "execution_count": 14,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Error: index out of range\n"
          ]
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "# ImportError is a built-in exception class in Python that is raised when a module or attribute cannot be imported.\n",
        "\n",
        "# When an import statement is executed, Python searches for the module or package in a list of directories that is stored in the sys.path variable. If the module cannot be found in any of these directories, or if there is an error while trying to load the module, an ImportError exception is raised.\n",
        "\n",
        "# In Python 3.6 and later versions, a new exception called ModuleNotFoundError was introduced. This exception is a subclass of ImportError and is raised specifically when a module is not found."
      ],
      "metadata": {
        "id": "S33lRi58pos1"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "# Catch only the exceptions you expect to occur, and let unexpected exceptions propagate up the call stack.\n",
        "\n",
        "# Use meaningful exception names that accurately describe the problem that occurred.\n",
        "\n",
        "# Provide helpful error messages that explain the problem and suggest a solution.\n",
        "\n",
        "# Handle exceptions at the appropriate level of granularity. For example, catch exceptions at the function level rather than at the module level, so that you can provide more specific error messages.\n",
        "\n",
        "# Use the finally clause to release resources (such as file handles or database connections) that were acquired in the try clause.\n",
        "\n",
        "# Don't use exceptions for flow control. Instead, use language constructs like if statements and loops to control program flow.\n",
        "\n",
        "# Don't catch exceptions that you can't handle. If you catch an exception and don't know what to do with it, re-raise it or let it propagate up the call stack.\n",
        "\n",
        "# Avoid catching and re-raising the same exception in the same block of code. This can lead to confusion and make it harder to debug problems.\n",
        "\n",
        "# Document the exceptions that your code can raise, along with their causes and recommended handling strategies.\n",
        "\n",
        "# Test your code thoroughly to ensure that it handles all expected exceptions correctly."
      ],
      "metadata": {
        "id": "Qlxe4gfup6oi"
      }
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "j2oZaw46psqn"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}